#1
Headless1s/Exercise41 pull request #2
Opened 2021-12-15 19:01 UTC by DitriXEDT

2021-12-15 19:59 UTC, NecroDog commented on Упражнение41/Forms/Форма/Ext/Form/Module.bsl
> +	Сообщить("Сделано все что надо! А остальное - подождет");
Вот тут хорошо

2021-12-15 19:59 UTC, NecroDog commented on Упражнение41/Forms/Форма/Ext/Form/Module.bsl
> +	ДобавимНекуюОшибку = 1/0;
А тут явно баг!

2021-12-15 20:01 UTC, NecroDog requested changes
Все сломается, надо бы поправить

2021-12-16 12:21 UTC, DitriXEDT commented on Упражнение41/Forms/Форма/Ext/Form/Module.bsl
> +	ДобавимНекуюОшибку = 1/0;
Исправил

2021-12-16 16:20 UTC, merged